name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
    build:
      name: Hello world action plus cmake
      runs-on: ubuntu-latest
      steps:
        - name: "Chekout"
          uses: actions/checkout@v1

        - name: "Default sh script"
          uses: ./action-a
          with:
            MY_NAME: "Jerry"

        - name: "Build CMake"
          uses: ashutoshvarma/action-cmake-build@v1

